### PR TITLE
Fix split_off function

### PR DESCRIPTION
**Pull request by Javier-varez**
With a real example, the split_off function doesn't seem to actually work (The BitIter after split_off is not correct and results in a random shift being applied, normally discarding one bit). 

I have fixed it so that it passes the test with a real-world SWD example transaction.

### CODE REVIEW

**Review by jonas-schievink — APPROVED** [review]
Thanks!

**Comment by Javier-varez** [comment]
Thanks for merging this! Is there any release planned for the future? It would be nice to have access to this fix without pinning it through the git repo, but it isn't a problem if it is not planned yet.

Thanks again!

**Comment by jonas-schievink** [comment]
I have some in-progress changes on master, I'll have to check out what their status is before releasing

**Comment by Javier-varez** [comment]
Sure, thanks a lot! There's no rush to release, I was just wondering.

**Pull request merged**
